apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: client
          image: docker.io/traefik/whoami:latest
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "3000"
          ports:
            - containerPort: 3000
              name: http-port
