apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: server
          image: docker.io/traefik/whoami:latest
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "5000"
          ports:
            - containerPort: 5000
              name: http-port
